{%- if values.componentName %}
  {%- set name = values.componentName %}
{%- else %}
  {%- set name = values.repoName %}
{% endif -%}

apiVersion: backstage.io/v1alpha1
{%- if values.entityKind %}
kind: ${{ values.entityKind }}
{%- else %}
kind: API
{%- endif %}
metadata:
  name: ${{ name }}
  {%- if values.title %}
  title: ${{ values.title }}
  {%- endif %}
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  annotations:
    backstage.io/source-location: url:https://${{ values.host }}/parasol/${{ values.repoName }}
    backstage.io/techdocs-ref: url:https://${{ values.host }}/parasol/envelope-parasol-catalog/-/tree/main/${{ values.repoName }}
    gitlab.com/project-slug: ${{ values.orgName }}/${{ values.repoName }}

spec:
  type: ${{ values.apiType }}
  {%- if values.system %}
  system: ${{ values.system }}
  {%- endif %}
  {%- if values.lifecycle %}
  lifecycle: ${{ values.lifecycle }}
  {%- else %}
  lifecycle: production
  {%- endif %}
  owner: ${{ values.owner }}
  definition:
    $text: ${{ values.apiPathText }}